#
# Copyright (C) 2024 The Android Open Source Project
# Copyright (C) 2024 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/samsung/a04e

# Architecture !
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_SUPPORTS_64_BIT_APPS := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a04e
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 300

# Partitions
BOARD_USES_METADATA_PARTITION := true
BOARD_DYNAMIC_PARTITION_ENABLE := true
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true # Builds super.img from build images in $PRODUCT_OUT
# Disable A/B Partitioning
AB_OTA_UPDATER := false
BOARD_USES_RECOVERY_AS_BOOT := false
TARGET_NO_RECOVERY := false
## odm.img
TARGET_COPY_OUT_ODM := odm
BOARD_ODMIMAGE_PARTITION_TYPE := f2fs
BOARD_ODMIMAGE_PARTITION_SIZE := 21389312
BOARD_PREBUILT_ODMIMAGE := $(DEVICE_PATH)/prebuilt/images/odm.img
## product.img
TARGET_COPY_OUT_PRODUCT := product
BOARD_PRODUCTIMAGE_PARTITION_TYPE := f2fs
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 1636524032
BOARD_PREBUILT_PRODUCTIMAGE := $(DEVICE_PATH)/prebuilt/images/product.img
## system_ext.img
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
BOARD_SYSTEM_EXTIMAGE_PARTITION_TYPE := f2fs
BOARD_SYSTEM_EXTIMAGE_PARTITION_SIZE := 306921472
BOARD_PREBUILT_SYSTEM_EXTIMAGE := $(DEVICE_PATH)/prebuilt/images/system_ext.img
## vendor.img 
TARGET_COPY_OUT_VENDOR := vendor
BOARD_VENDORIMAGE_PARTITION_TYPE := f2fs
BOARD_VENDORIMAGE_PARTITION_SIZE := 686198784
BOARD_PREBUILT_VENDORIMAGE := $(DEVICE_PATH)/prebuilt/images/vendor.img
## system.img
BOARD_SYSTEMIMAGE_PARTITION_TYPE := f2fs
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 4014456832
## super.img 
BOARD_SUPER_PARTITION_SIZE := 6786383872 # TODO: Fix hardcoded value
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm system_ext # List of partitions in your stock super.img
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 6786383872 # TODO: Fix hardcoded value

# Platform
TARGET_BOARD_PLATFORM := mt6765